--
-- PostgreSQL database dump
--

\restrict yjyjzDb85YK1HQ1oF8Pexxh7SSQIwRgH85a22ObL50TcZ8KgEWk2x984yQRc5CX

-- Dumped from database version 15.19
-- Dumped by pg_dump version 15.19

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    actor_role character varying(255) NOT NULL,
    after_data text,
    before_data text,
    object_id bigint,
    object_type character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    actor_id bigint
);


ALTER TABLE public.audit_logs OWNER TO postgres;

--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: buildings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.buildings (
    id bigint NOT NULL,
    active boolean NOT NULL,
    address character varying(255) NOT NULL,
    floors integer NOT NULL,
    name character varying(255) NOT NULL,
    note character varying(1000),
    manager_id bigint,
    landlord_id bigint NOT NULL
);


ALTER TABLE public.buildings OWNER TO postgres;

--
-- Name: buildings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.buildings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buildings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token character varying(100) NOT NULL,
    used boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.password_reset_tokens OWNER TO postgres;

--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    revoked boolean NOT NULL,
    token character varying(500) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.refresh_tokens OWNER TO postgres;

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permissions (
    id bigint NOT NULL,
    permission character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT role_permissions_role_check CHECK (((role)::text = ANY ((ARRAY['TENANT'::character varying, 'LANDLORD'::character varying, 'MANAGER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.role_permissions OWNER TO postgres;

--
-- Name: role_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rooms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rooms (
    id bigint NOT NULL,
    area double precision NOT NULL,
    code character varying(255) NOT NULL,
    floor integer NOT NULL,
    max_people integer NOT NULL,
    rent bigint NOT NULL,
    status character varying(255) NOT NULL,
    building_id bigint NOT NULL,
    CONSTRAINT rooms_status_check CHECK (((status)::text = ANY ((ARRAY['EMPTY'::character varying, 'DEPOSITED'::character varying, 'RENTED'::character varying, 'STOPPED'::character varying])::text[])))
);


ALTER TABLE public.rooms OWNER TO postgres;

--
-- Name: rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_price_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_price_history (
    id bigint NOT NULL,
    effective_from date NOT NULL,
    price bigint NOT NULL,
    service_id bigint NOT NULL
);


ALTER TABLE public.service_price_history OWNER TO postgres;

--
-- Name: service_price_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_price_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_price_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services (
    id bigint NOT NULL,
    active boolean NOT NULL,
    description character varying(500),
    name character varying(255) NOT NULL,
    price bigint NOT NULL,
    calculation_method character varying(255),
    unit character varying(255)
);


ALTER TABLE public.services OWNER TO postgres;

--
-- Name: services_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tenant_profiles (
    id bigint NOT NULL,
    citizen_id character varying(255),
    date_of_birth character varying(255),
    hometown character varying(255),
    id_back_url character varying(255),
    id_front_url character varying(255),
    job character varying(255),
    user_id bigint NOT NULL
);


ALTER TABLE public.tenant_profiles OWNER TO postgres;

--
-- Name: tenant_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tenant_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenant_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(10) NOT NULL,
    role character varying(255) NOT NULL,
    locked_until timestamp(6) without time zone,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL,
    must_change_password boolean DEFAULT false NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['TENANT'::character varying, 'LANDLORD'::character varying, 'MANAGER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: audit_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.audit_logs (id, action, actor_role, after_data, before_data, object_id, object_type, "timestamp", actor_id) FROM stdin;
1	CREATE	LANDLORD	{"id":8,"floor":4,"code":"401","area":25.5,"buildingId":2,"status":"EMPTY","maxPeople":3,"rent":2500000}	\N	8	ROOM	2026-09-26 23:56:10.462028	12
2	UPDATE	LANDLORD	{"id":8,"floor":4,"rent":2700000,"maxPeople":3,"code":"401","area":26.0,"status":"EMPTY"}	{"id":8,"floor":4,"rent":2500000,"maxPeople":3,"code":"401","area":25.5,"status":"EMPTY"}	8	ROOM	2026-09-27 00:04:35.979993	12
3	UPDATE	LANDLORD	{"status":"STOPPED","id":8,"code":"401"}	{"status":"EMPTY","id":8,"code":"401"}	8	ROOM	2026-09-27 00:14:48.09879	12
4	CREATE	LANDLORD	{"status":"EMPTY","buildingId":3,"area":20.0,"code":"101","floor":1,"id":9,"rent":3000000,"maxPeople":2}	\N	9	ROOM	2026-09-27 17:19:54.811576	13
\.


--
-- Data for Name: buildings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.buildings (id, active, address, floors, name, note, manager_id, landlord_id) FROM stdin;
1	t	123 Đường ABC, Phường XYZ, Hà Nội	5	Tòa TroRoom A	Tòa demo cho sinh viên	\N	11
2	f	789 Đường Test, Hà Nội	5	Tòa Landlord Moi - Da Sua	Đã cập nhật thông tin	\N	12
3	t	Trung tâm thành phố	3	A	\N	14	13
\.


--
-- Data for Name: password_reset_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.password_reset_tokens (id, created_at, expires_at, token, used, user_id) FROM stdin;
1	2026-09-25 17:41:13.790546	2026-09-25 18:11:13.790546	5848c20b-9dab-4ad4-aa1e-0d97ad77e453	t	1
2	2026-09-25 22:58:15.466777	2026-09-25 23:28:15.466777	859b613a-fc02-415f-b51e-94bb65b01f54	t	1
3	2026-09-25 23:56:16.873162	2026-09-26 00:26:16.873162	8d2062d3-633d-4383-aeac-dd380d80b259	f	1
4	2026-09-26 00:30:22.900994	2026-09-26 01:00:22.900994	9df43e2e-e896-4d07-83bf-6970dd25e5a7	t	1
5	2026-09-26 01:29:53.226166	2026-09-26 01:59:53.226166	fcf6f9e5-326f-4c13-a031-3f5809f950eb	f	2
\.


--
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.refresh_tokens (id, expires_at, revoked, token, user_id) FROM stdin;
1	2026-10-01 13:29:40.94281	f	4cdb751b-8fe1-411f-8589-2f2bcc02b564	1
2	2026-10-01 13:33:33.100643	f	0678224f-b72a-4940-8e2f-ae1dff7cf6dc	1
3	2026-10-01 13:57:01.94256	f	20c3f7a7-f008-43a2-adb1-d05fe90b236c	1
4	2026-10-01 14:27:10.646302	f	804b9d7d-c61f-4db9-9209-387b0c7c5b79	1
5	2026-10-01 14:31:38.859566	t	353bf32e-b6ad-469d-8a2e-ff4181ca25bf	1
6	2026-10-01 15:32:55.630558	f	297344cd-fa3e-4758-b7a1-58812d3b9aa4	2
7	2026-10-01 15:33:22.822855	f	585fb261-aa62-4096-995d-c37f6ea1d37f	2
8	2026-10-01 20:22:52.579507	f	baed73e0-5a7a-4413-994d-932219f6f4bf	4
9	2026-10-01 20:23:50.797329	f	8f1ccfa6-be47-401e-9f9d-961ce5d4d216	4
10	2026-10-01 20:42:17.606445	f	08505813-31fa-4868-86dd-28b8a54a29d9	4
11	2026-10-01 20:45:35.214605	f	c5f798cd-3b87-4e1b-ad76-8fee49004bce	4
12	2026-10-01 22:01:59.847394	f	c6a3fc7d-a766-4503-96d0-6c8b61d5e1a0	7
13	2026-10-01 22:21:02.838688	f	a7ec0571-007e-4545-8225-fef79afc2015	4
14	2026-10-02 11:35:14.035421	f	aa3cd2ff-2a9e-4974-8440-79d12726cfe8	7
15	2026-10-02 11:37:24.760165	f	152d96cc-5a16-438e-84b0-4caa6079b68d	4
16	2026-10-02 12:09:31.169638	f	0bc98f02-2879-4f36-943c-9b02c168341c	4
17	2026-10-02 13:02:18.583714	f	69fd74f1-3fbc-48a5-ae91-310b4d41a6d0	4
18	2026-10-03 00:57:56.911226	f	95ac21c8-3dca-4c71-9496-3e39da3e98d0	8
19	2026-10-03 00:58:19.968297	f	3b062eff-3d02-4116-86af-7ba2dc569332	8
20	2026-10-03 01:01:25.469658	t	84b8c80c-0088-4213-a7ca-f2992a0377ff	8
21	2026-10-03 01:45:22.447921	f	a196f062-74ec-4c93-bac0-3a91e777bd27	10
22	2026-10-03 01:45:25.652113	f	43af492e-2e35-48ce-a9a0-344840efc389	10
23	2026-10-03 01:52:25.534481	f	b285a071-1965-4d2e-990e-95af8d50b217	10
24	2026-10-03 01:55:40.560363	f	a3e4c137-fcc8-4160-8a58-7168ac8f119f	10
25	2026-10-03 01:56:35.760917	f	684b00cb-0f99-4031-9fe1-20efa1d40d6e	10
26	2026-10-03 02:06:05.459991	f	43a01c92-9d84-4636-ad8b-effaae5b7d17	10
27	2026-10-03 02:08:19.363948	f	371e76d7-6911-4306-b900-7c4898917017	10
28	2026-10-03 03:17:21.32552	f	6c168f48-8d65-461a-9b10-515def403b66	10
29	2026-10-03 03:20:04.532504	f	faa3cce4-0b1f-465a-a419-ae49a2b1e886	10
30	2026-10-03 03:23:33.059788	f	5a9434d0-c097-48cb-9ba3-0dea0b71fcc0	10
31	2026-10-03 03:35:42.556868	f	7952ac76-3957-4cde-9e38-bf02af0df75d	7
32	2026-10-03 12:35:10.802639	f	8b3076cf-d259-4310-80ff-a114b02ee67d	7
33	2026-10-03 12:45:35.785011	f	96053875-528a-4d04-bfe4-1b3c4d59c0fd	7
34	2026-10-03 12:46:38.267362	f	6e3ea2ed-efec-4fc0-b9ba-9c83054f69aa	11
35	2026-10-03 13:51:25.646128	f	d7ec1c11-6333-4354-a633-7e50bdb078e7	7
36	2026-10-03 13:54:24.50989	f	55295026-2d9b-48de-89eb-9968335a9206	12
37	2026-10-03 14:28:31.288865	f	63284738-68a8-43fa-a0d1-9052d54cd62e	12
38	2026-10-03 15:11:15.044952	f	d4d58737-3635-4a34-ad9f-f48c1176b3b5	12
39	2026-10-03 16:13:59.829884	f	8f84eec1-cb7d-49cb-87fc-e88fef86f858	12
40	2026-10-03 19:48:26.806326	f	5b147e9d-a166-4d1b-acd6-e184a4eead01	12
41	2026-10-03 20:24:16.317026	f	c92f90b4-36d7-424b-aa99-0b96b6481f7f	12
42	2026-10-03 21:33:44.090842	f	83dbb444-1653-48c1-963b-2a69349c873b	12
43	2026-10-03 22:44:11.882323	f	18b4071e-28b2-4554-8c5c-6550efb43099	12
44	2026-10-03 23:46:10.931772	f	3f4c6263-bd9d-46be-8b96-45aaf01d6823	12
45	2026-10-04 00:28:25.472902	f	aa1a78f8-2a7c-48a0-b423-13a7b9ba8e69	7
46	2026-10-04 00:40:47.495347	f	1d400df4-8837-4dfb-b495-9da12a307d49	7
47	2026-10-04 01:20:48.956968	t	5b13aa1c-2e58-4334-a418-74c149cffa69	7
48	2026-10-04 01:42:16.942758	t	1cda0809-724f-4286-9031-9bd7d4239862	12
49	2026-10-04 01:51:24.551735	t	c8c47856-cf5b-4a25-938d-fc04ff3ac968	7
50	2026-10-04 02:04:14.520552	t	cf75381f-ea40-4d60-86bc-cc4008e32e58	12
51	2026-10-04 02:36:46.395338	t	508cba54-bddc-4c6e-9ce7-afe0341b9d5f	12
52	2026-10-04 14:32:51.117374	t	ca74cd25-e9b4-48a0-a739-3c7b7f0d543a	12
53	2026-10-04 14:54:51.4875	t	82f31aef-0832-4609-b0e8-8a99b2aa7c9e	12
54	2026-10-04 14:58:43.392689	t	0069e1cb-bb0a-4289-8eb6-82b6ec1212a1	7
55	2026-10-04 15:02:12.751393	t	d8ef0b0a-cfb5-4a43-92e0-b98a9c1573ac	7
56	2026-10-04 15:35:21.041238	f	b1decf8d-3142-4120-9f48-800aab4e6146	7
57	2026-10-04 15:39:23.604457	f	e623f722-b7f9-4302-a12b-4389a5e6ea12	7
58	2026-10-04 15:39:28.331777	f	7c54b5cc-07af-49e3-95be-da524063ab69	7
59	2026-10-04 15:39:34.874111	t	d107fd9b-5492-4020-9b8a-85f3b46b4cbe	7
60	2026-10-04 15:49:02.140493	t	a9c3b3fe-45a7-4b27-a4d2-ddc4952d77eb	7
61	2026-10-04 15:59:50.10984	t	63e7132d-102d-43c6-8197-9feca5748495	7
62	2026-10-04 16:10:58.829676	t	9be2dc1d-4706-4e7d-a1ff-c3cf78fda256	15
63	2026-10-04 16:14:33.693322	t	d1530fb2-1416-4df2-9966-1af6a42e0d0a	14
64	2026-10-04 16:37:57.379557	t	b2e01b2c-c78b-488f-861f-97ad2d123e58	13
65	2026-10-04 16:45:02.520932	t	ccd16f99-5ccd-44f3-a047-65d377c3648f	7
66	2026-10-04 16:45:31.419457	t	c4c6edf3-ca43-4786-a5d4-150447d28f65	13
67	2026-10-04 16:46:03.632272	t	9dfffa8d-706e-4bfb-aa49-9225e524ca5c	14
68	2026-10-04 16:58:19.215361	t	2e60d6b6-e3b6-47e8-a98a-bd36a69018ef	14
69	2026-10-04 17:03:04.090796	t	9d23b3e6-5a7c-40ff-921f-d5d7578631d9	14
70	2026-10-04 17:03:10.753685	t	64198097-17a9-433c-9fec-6a57cc07f0e7	14
71	2026-10-04 17:05:05.979817	t	09e9380e-84e9-46bc-b993-9f4606ff845b	13
72	2026-10-04 17:18:55.636679	t	67ad7b83-ea4c-439b-b433-19e1b1f30214	13
73	2026-10-04 17:20:07.456606	t	62fa9f61-88e3-4dfe-8dda-1dbe021e8a13	14
74	2026-10-04 17:20:46.379273	t	75437d20-9c8e-42b7-b282-fa9547aca376	13
75	2026-10-04 17:20:54.680122	t	788ecdd6-8038-407c-828e-b94881aac7d3	7
76	2026-10-04 17:21:26.581228	t	8e423653-0076-4c94-8586-88dfebd63f67	14
77	2026-10-04 17:25:17.372543	t	89cf59f1-7953-4943-a8cc-0245cd837a97	14
78	2026-10-04 17:27:14.302768	t	0097f449-b925-40bc-a9de-9adc2639d9b7	14
79	2026-10-04 17:29:35.767942	t	18ca68d2-9c05-465e-a51c-e6a318d1e279	7
80	2026-10-04 17:30:19.964001	t	41637505-9e8d-410a-a847-5080f905dc2a	7
81	2026-10-04 17:32:40.583497	t	f3bc777a-20e7-403e-8576-609cbb34aa55	7
82	2026-10-04 17:33:12.965644	t	ac916dc1-7cfe-40a0-b8fd-20ee5286d524	13
83	2026-10-04 17:33:57.3907	f	57aea03d-6e8a-4148-9a60-20612072efc1	14
84	2026-10-04 17:57:07.298837	f	ebe12b43-2909-4d1f-90ef-042aa069554c	14
85	2026-10-04 20:30:01.655839	f	25652cfa-273e-490b-9397-96ef9e47f53c	13
86	2026-10-05 19:46:39.718259	t	188c746e-ea6e-4f88-845b-18f4b2c65d3b	13
87	2026-10-05 19:47:32.68672	f	31188aaa-d23a-4223-89fb-819d6526c386	7
\.


--
-- Data for Name: role_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.role_permissions (id, permission, role) FROM stdin;
1	ADMIN_ACCESS	ADMIN
2	BUILDING_MANAGE	LANDLORD
3	ROOM_MANAGE	LANDLORD
5	ROOM_MANAGE	MANAGER
6	PROFILE_VIEW	TENANT
7	SERVICE_MANAGE	LANDLORD
8	BUILDING_MANAGE	MANAGER
9	SERVICE_MANAGE	MANAGER
\.


--
-- Data for Name: rooms; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rooms (id, area, code, floor, max_people, rent, status, building_id) FROM stdin;
1	26.5	101	1	3	2600000	RENTED	2
2	25.5	201	2	3	2500000	EMPTY	2
3	25.5	202	2	3	2500000	EMPTY	2
4	25.5	203	2	3	2500000	EMPTY	2
5	25.5	301	3	3	2500000	EMPTY	2
6	25.5	302	3	3	2500000	EMPTY	2
7	25.5	303	3	3	2500000	EMPTY	2
8	26	401	4	3	2700000	STOPPED	2
9	20	101	1	2	3000000	EMPTY	3
\.


--
-- Data for Name: service_price_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.service_price_history (id, effective_from, price, service_id) FROM stdin;
1	2026-09-01	4000	1
2	2026-09-01	18000	2
3	2026-09-01	100000	3
4	2026-10-01	120000	3
\.


--
-- Data for Name: services; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.services (id, active, description, name, price, calculation_method, unit) FROM stdin;
2	t	Giá nước mới theo m3	Nước	18000	BY_METER	m3
3	t	Internet hang thang	Internet	120000	FIXED_ROOM	phong
4	t	Phí thu gom rác hàng tháng	Rác	30000	FIXED_ROOM	phong
5	t	Phí gửi xe hàng tháng	Gửi xe	100000	BY_PERSON	nguoi
1	t	Giá điện mới theo kWh	Điện	4000	BY_METER	kWh
6	f	đá	đ	2222	BY_METER	d
7	f	sdad	đâf	222	BY_PERSON	đá
\.


--
-- Data for Name: tenant_profiles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tenant_profiles (id, citizen_id, date_of_birth, hometown, id_back_url, id_front_url, job, user_id) FROM stdin;
1	012345678901	2006-10-17	Thái Nguyên	uploads\\profile\\1790367869056_back.png	uploads\\profile\\1790367869050_front.png	Sinh viên	10
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, name, password, phone, role, locked_until, failed_login_attempts, active, must_change_password) FROM stdin;
3	landlord3@test.com	Nguyen Van B	$2a$10$XPvP27LfxUo.2npB1vEi.u9rzvIrtAZUjOlyAlilsjkg6oSAyl9sy	0971112233	LANDLORD	\N	0	t	t
13	landlord@test.com	Chủ nhà 	$2a$10$yeHAEFAftwDJysIUXWKiK.eQkkIcUhKWYOZQbtOMM1R4eFYpbyXPm	0988888001	LANDLORD	\N	0	t	t
14	manager@test.com	Quản lý	$2a$10$HKiFCPMEZ5oGSoHfEH69leUUONuMONdl2RTO29vVr5ew94UV49.Xe	0988888002	MANAGER	\N	0	t	t
15	tenant@test.com	Người thuê	$2a$10$VxA9d7HouYtLoS4SALBAROvmIUmKVps6YEOFmNk7JKBldMZFQ8fcy	0988888003	TENANT	\N	0	t	f
7	admin@troroom.com	System Admin	$2a$10$R7mFShQ8SCSOeWJScOUOQeR7pi/VpfzTo9QC0mxYRBTZCoIlb7bua	0900000000	ADMIN	\N	0	t	f
2	dtc245200380@ictu.edu.vn	Test User	$2a$10$/J/hbnInesEv8ynGB13w7enUYfTGJO5BsQbj4cYYOyeX6cxEbouJ6	0987654321	TENANT	\N	0	t	f
1	test@gmail.com	Nguyen Van A	$2a$10$zy4rbNVOfcnI6Xwk5EN1PeOXNvwvU/bhmOD4mFPtScshWMyEglaE6	0912345678	TENANT	\N	0	t	f
8	register@test.com	Test Register	$2a$10$JKJw5vUqCh45oC/aE5PNOeLVKWXkRxU5RdksKB3hRXIquu.E.Z2xu	0981234567	TENANT	\N	0	t	f
9	locktest@test.com	Lock Test	$2a$10$xWj4n5.1L.8VCk6M.4fEeOqdL3hcDzNwmYkfV1/XPknyA.WtSMN6i	0981234570	TENANT	2026-09-26 01:14:04.478835	0	t	f
10	faceghost13tn@gmail.com	NGUYEN VIET ANH	$2a$10$EzFktIhGvOkm3so9jVC6reECbh/d.2rReXoGLqsz4TQ7YT767ldpm	0862539833	TENANT	\N	0	t	f
11	landlord-s107@gmail.com	Landlord S107	$2a$10$iCSyTtQgiWd8mdpZtMmRj.eVZ6eaE4dFymN08xgVjjaBrTxCgOGJ2	0988888877	LANDLORD	\N	0	t	t
4	testlandlord@test.com	Test Landlord	$2a$10$lhkoVqT6pL5NEpxIz7tiS.YOEWEi2qWLOyQ/5cXqKMlnDu1APKx8y	0971112234	LANDLORD	2026-09-26 12:29:16.319576	3	t	f
12	landlord107@test.com	Landlord Test S107	$2a$10$Zxb8CCbH6nwueljrukyqCOXIquBaGDt75P9F96gEK.G0TrPOJUVz.	0988888866	LANDLORD	\N	0	t	t
\.


--
-- Name: audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.audit_logs_id_seq', 4, true);


--
-- Name: buildings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.buildings_id_seq', 3, true);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.password_reset_tokens_id_seq', 5, true);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.refresh_tokens_id_seq', 87, true);


--
-- Name: role_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_permissions_id_seq', 9, true);


--
-- Name: rooms_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rooms_id_seq', 9, true);


--
-- Name: service_price_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.service_price_history_id_seq', 4, true);


--
-- Name: services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.services_id_seq', 7, true);


--
-- Name: tenant_profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tenant_profiles_id_seq', 1, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 15, true);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: buildings buildings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buildings
    ADD CONSTRAINT buildings_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);


--
-- Name: service_price_history service_price_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_price_history
    ADD CONSTRAINT service_price_history_pkey PRIMARY KEY (id);


--
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


--
-- Name: tenant_profiles tenant_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenant_profiles
    ADD CONSTRAINT tenant_profiles_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: rooms uk_room_building_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT uk_room_building_code UNIQUE (building_id, code);


--
-- Name: users ukdu5v5sr43g5bfnji4vb8hg5s3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukdu5v5sr43g5bfnji4vb8hg5s3 UNIQUE (phone);


--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);


--
-- Name: tenant_profiles ukgwx1m8u7jsu1aoxmrxgvyi66j; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenant_profiles
    ADD CONSTRAINT ukgwx1m8u7jsu1aoxmrxgvyi66j UNIQUE (user_id);


--
-- Name: role_permissions ukiwqx0wbmqmamukl6hmqgyjf2m; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT ukiwqx0wbmqmamukl6hmqgyjf2m UNIQUE (role, permission);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: buildings fk_buildings_landlord; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buildings
    ADD CONSTRAINT fk_buildings_landlord FOREIGN KEY (landlord_id) REFERENCES public.users(id);


--
-- Name: audit_logs fkf2uqqjmo7gvd8fq7ac81fgc0m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fkf2uqqjmo7gvd8fq7ac81fgc0m FOREIGN KEY (actor_id) REFERENCES public.users(id);


--
-- Name: tenant_profiles fkgqik779nn4t69onjva08qkdj4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenant_profiles
    ADD CONSTRAINT fkgqik779nn4t69onjva08qkdj4 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: password_reset_tokens fkk3ndxg5xp6v7wd4gjyusp15gq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: rooms fkojgn0sxhkfxd7pmmojnem9r4q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT fkojgn0sxhkfxd7pmmojnem9r4q FOREIGN KEY (building_id) REFERENCES public.buildings(id);


--
-- Name: service_price_history fkqj0ssvod7eqhsbakgu08bm3hj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_price_history
    ADD CONSTRAINT fkqj0ssvod7eqhsbakgu08bm3hj FOREIGN KEY (service_id) REFERENCES public.services(id);


--
-- Name: buildings fks0en8l3jvg2tn2eji1pur17p6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buildings
    ADD CONSTRAINT fks0en8l3jvg2tn2eji1pur17p6 FOREIGN KEY (manager_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict yjyjzDb85YK1HQ1oF8Pexxh7SSQIwRgH85a22ObL50TcZ8KgEWk2x984yQRc5CX

